[development]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
postgres = { url = "postgres://joao@localhost/dework?sslmode=disable" }

[staging]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }