// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct Company {
    pub id: i32,
    pub name: String,
    pub github: String,
    pub private_key: String,
    pub balance: Option<i32>,
    pub created_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Contribution {
    pub id: i32,
    pub pull_request: String,
    pub type_: String,
    pub merged: Option<bool>,
    pub balance: Option<i32>,
    pub vote_balance: Option<i32>,
    pub story_id: i32,
    pub created_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Story {
    pub id: i32,
    pub pull_request: String,
    pub type_: String,
    pub merged: Option<bool>,
    pub balance: Option<i32>,
    pub vote_balance: Option<i32>,
    pub company_id: i32,
    pub created_at: NaiveDateTime,
}
pub mod user {
    #[derive(Queryable, Debug)]
    pub struct UserCompany {
        pub id: i32,
        pub company_id: i32,
        pub user_id: i32,
    }
}

#[derive(Queryable, Debug)]
pub struct UserContribution {
    pub id: i32,
    pub company_id: i32,
    pub contribution_id: i32,
    pub balance: Option<i32>,
    pub vote_balance: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub public_key: String,
    pub job: String,
    pub created_at: NaiveDateTime,
}
